# Site settings
title: Zem
email: dan@zem.org.uk
description: >
  My own corner of the Internet.
baseurl: ""
#url: "http://www.zem.org.uk" # the base hostname & protocol for your site
twitter_username: DanF42 
github_username:  danfoster
#theme: jekyll-theme-hacker
#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: post

analytics :
  provider : google
  google : 
      tracking_id : 'UA-44620677-1'
