# Site settings
title: Zem
email: dan@zem.org.uk
description: > # this means to ignore newlines until "baseurl:"
  My own corner of the Internet.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.zem.org.uk" # the base hostname & protocol for your site
twitter_username: DanF42 
github_username:  danfoster

# Build settings
#markdown: kramdown
markdown: redcarpet
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: post

redcarpet:
  extensions: ['tables']
